version: '3.3'
services:
  # Mongo Service
  mongo-dev:
    image: mongo:3.4
    ports:
      - "27017:27017"
    expose:
      # Opens port 27017 on the container
      - '27017'
      # Where our data will be persisted
    volumes:
      - ./mongo/mongod-entrypoint-scripts:/docker-entrypoint-initdb.d:rw
      - mongo_volume_db:/var/lib/mysql:rw
      - ./mongod/mongod.cnf:/etc/mongod/mongod.cnf
    container_name: mongo-dev
    networks:
      mongo_dev_net:
        ipv4_address: 10.0.0.102
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    security_opt:
      - 'seccomp:unconfined'
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
  mongo-seed:
    image: mongo:3.4
    links:
      - mongodb
    volumes:
      - ./seed-data:/seed-data
    command: 'bash -c "mongoimport --host mongodb --type json --file /seed-data/projects.json --jsonArray"'